# Generated by Django 4.0.2 on 2022-04-06 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=128, verbose_name='Короткое наименование')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_actual', models.BooleanField(default=False, verbose_name='Актуальность справочника')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='Дата начала действия справочника')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания справочника')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения справочника')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
                'ordering': ['pk', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DirectoryVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Версия справочника')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbook.directory', verbose_name='Справочник')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Версия справочника',
                'verbose_name_plural': 'Версий справочника',
                'ordering': ['pk', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DirectoryElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Элемент справочника')),
                ('description', models.TextField(verbose_name='Значение элемента')),
                ('directory_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbook.directoryversion', verbose_name='Справочник версия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Элемент справочника',
                'verbose_name_plural': 'Элементы справочника',
                'ordering': ['pk', 'title'],
            },
        ),
    ]
