# Generated by Django 4.0.2 on 2022-04-05 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0002_alter_directoryelement_directory_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directory',
            options={'ordering': ['pk', 'title'], 'verbose_name': 'Справочник', 'verbose_name_plural': 'Справочники'},
        ),
        migrations.AlterModelOptions(
            name='directoryelement',
            options={'ordering': ['pk', 'title'], 'verbose_name': 'Элемент справочника', 'verbose_name_plural': 'Элементы справочника'},
        ),
        migrations.AlterModelOptions(
            name='directoryversion',
            options={'ordering': ['pk', 'title'], 'verbose_name': 'Версия справочника', 'verbose_name_plural': 'Версий справочника'},
        ),
        migrations.RemoveField(
            model_name='directory',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='directoryelement',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='directoryversion',
            name='uuid',
        ),
    ]
